## Практическое задание к уроку "Урок 2. Матрицы и матричные операции. Часть 1"

In [1]:
from sympy import *
import numpy as np
from numpy.linalg import *

Все задания рекомендуется делать вручную, затем проверяя полученные результаты с использованием numpy.

__1.__ **Установить, какие произведения матриц $AB$ и $BA$ определены, и найти размерности полученных матриц:  
а) $A$ — матрица $4\times 2$, $B$ — матрица $4\times 2$;  
б) $A$ — матрица $2\times 5$, $B$ — матрица $5\times 3$;  
в) $A$ — матрица $8\times 3$, $B$ — матрица $3\times 8$;  
г) $A$ — квадратная матрица $4\times 4$, $B$ — квадратная матрица $4\times 4$.**

**а)** $A$ — матрица $4\times 2$, $B$ — матрица $4\times 2$;  
Произведения $AB$ и $BA$ не определены, так как количество столбцов A и количество строк B должны совпадать в случае $AB$, а в случае $BA$ количество столбцов B и количество строк A должны совпадать.

**б)** $A$ — матрица $2\times 5$, $B$ — матрица $5\times 3$;  
Произведение $AB$ определено, так как количество столбцов A и количество строк B совпадает - 5. Итоговая матрица будет иметь размер по строкам A и по столбцам B - 2x3.  
Произведение $BA$ не определено, так как количество столбцов B и количество строк A должны совпадать.

In [2]:
# проверка
A = np.ones((2, 5))
A

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [3]:
B = np.ones((5, 3))
B

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [4]:
C = np.dot(A, B)
C

array([[5., 5., 5.],
       [5., 5., 5.]])

In [5]:
C.shape

(2, 3)

**в)** $A$ — матрица $8\times 3$, $B$ — матрица $3\times 8$;  
Произведение $AB$ определено, так как количество столбцов A и количество строк B совпадает - 3. Итоговая матрица будет иметь размер по строкам A и по столбцам B - 8x8.  
Произведение $BA$ определено, так как количество столбцов B и количество строк A совпадает - 8. Итоговая матрица будет иметь размер по строкам B и по столбцам A - 3x3.

In [6]:
# проверка
A = np.ones((8, 3))
A

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [7]:
B = np.ones((3, 8))
B

array([[1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.]])

In [8]:
C1 = np.dot(A, B)
C1

array([[3., 3., 3., 3., 3., 3., 3., 3.],
       [3., 3., 3., 3., 3., 3., 3., 3.],
       [3., 3., 3., 3., 3., 3., 3., 3.],
       [3., 3., 3., 3., 3., 3., 3., 3.],
       [3., 3., 3., 3., 3., 3., 3., 3.],
       [3., 3., 3., 3., 3., 3., 3., 3.],
       [3., 3., 3., 3., 3., 3., 3., 3.],
       [3., 3., 3., 3., 3., 3., 3., 3.]])

In [9]:
C1.shape

(8, 8)

In [10]:
C2 = np.dot(B, A)
C2

array([[8., 8., 8.],
       [8., 8., 8.],
       [8., 8., 8.]])

In [11]:
C2.shape

(3, 3)

**г)** $A$ — квадратная матрица $4\times 4$, $B$ — квадратная матрица $4\times 4$.  
Произведение $AB$ определено, так как количество столбцов A и количество строк B совпадает - 4. Итоговая матрица будет иметь размер по строкам A и по столбцам B - 4x4.  
Произведение $BA$ определено, так как количество столбцов B и количество строк A совпадает - 4. Итоговая матрица будет иметь размер по строкам B и по столбцам A - 4x4.

In [12]:
# проверка
A = np.ones((4, 4))
A

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [13]:
B = np.ones((4, 4))
B

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [14]:
C1 = np.dot(A, B)
C1

array([[4., 4., 4., 4.],
       [4., 4., 4., 4.],
       [4., 4., 4., 4.],
       [4., 4., 4., 4.]])

In [15]:
C1.shape

(4, 4)

In [16]:
C2 = np.dot(B, A)
C2

array([[4., 4., 4., 4.],
       [4., 4., 4., 4.],
       [4., 4., 4., 4.],
       [4., 4., 4., 4.]])

In [17]:
C2.shape

(4, 4)

__2.__ **Найти сумму и произведение матриц $A=\begin{pmatrix}
1 & -2\\ 
3 & 0
\end{pmatrix}$ и $B=\begin{pmatrix}
4 & -1\\ 
0 & 5
\end{pmatrix}.$**

Вручную:  
1) сумма:  
$A + B = \begin{pmatrix}
1 & -2\\ 
3 & 0
\end{pmatrix} +\begin{pmatrix}
4 & -1\\ 
0 & 5
\end{pmatrix} = \begin{pmatrix}
1+4 & -2-1\\ 
3+0 & 0+5
\end{pmatrix} = \begin{pmatrix}
5 & -3\\ 
3 & 5
\end{pmatrix}$  
2) произведение:  
$A \cdot B = \begin{pmatrix}
1 & -2\\ 
3 & 0
\end{pmatrix} \cdot\begin{pmatrix}
4 & -1\\ 
0 & 5
\end{pmatrix} = \begin{pmatrix}
1 \cdot 4 + (-2)\cdot0 & 1\cdot(-1) + (-2) \cdot 5\\
3 \cdot 4 + 0 \cdot 0 & 3\cdot(-1) + 0 \cdot 5
\end{pmatrix} = \begin{pmatrix}
4 & -11\\ 
12 & -3
\end{pmatrix}$

$B \cdot A = \begin{pmatrix}
4 & -1\\ 
0 & 5
\end{pmatrix} \cdot \begin{pmatrix}
1 & -2\\ 
3 & 0
\end{pmatrix} = \begin{pmatrix}
4 \cdot 1 + (-1)\cdot3 & 4\cdot(-2) + (-1) \cdot 0\\
0 \cdot 1 + 5 \cdot 3 & 0\cdot(-2) + 5 \cdot 0
\end{pmatrix} = \begin{pmatrix}
1 & -8\\ 
15 & 0
\end{pmatrix}$

In [18]:
# проверка
A = np.array([[1, -2], [3, 0]])
A

array([[ 1, -2],
       [ 3,  0]])

In [19]:
B = np.array([[4, -1], [0, 5]])
B

array([[ 4, -1],
       [ 0,  5]])

In [20]:
# сумма
A + B

array([[ 5, -3],
       [ 3,  5]])

In [21]:
# произведение
np.dot(A, B)

array([[  4, -11],
       [ 12,  -3]])

In [22]:
np.dot(B, A)

array([[ 1, -8],
       [15,  0]])

__3.__ **Из закономерностей сложения и умножения матриц на число можно сделать вывод, что матрицы одного размера образуют линейное пространство. Вычислить линейную комбинацию $3A-2B+4C$ для матриц $A=\begin{pmatrix}
1 & 7\\ 
3 & -6
\end{pmatrix}$, $B=\begin{pmatrix}
0 & 5\\ 
2 & -1
\end{pmatrix}$, $C=\begin{pmatrix}
2 & -4\\ 
1 & 1
\end{pmatrix}.$**

Вручную:  
При умножении матрицы на число, на число умножаются все элементы матрицы:  
$3\cdot A=3\cdot\begin{pmatrix}
1 & 7\\ 
3 & -6
\end{pmatrix} = \begin{pmatrix}
3\cdot1 & 3\cdot7\\ 
3\cdot3 & 3\cdot(-6)
\end{pmatrix} = \begin{pmatrix}
3 & 21\\ 
9 & -18
\end{pmatrix}$  
Так как матрицы можем только складывать (вычитать не можем), то коэффициент для матрицы B равен -2.  
$-2\cdot B=-2\cdot\begin{pmatrix}
0 & 5\\ 
2 & -1
\end{pmatrix} = \begin{pmatrix}
-2\cdot0 & -2\cdot5\\ 
-2\cdot2 & -2\cdot(-1)
\end{pmatrix} = \begin{pmatrix}
0 & -10\\ 
-4 & 2
\end{pmatrix}$

$4\cdot C=4\cdot\begin{pmatrix}
2 & -4\\ 
1 & 1
\end{pmatrix} = \begin{pmatrix}
4\cdot2 & 4\cdot(-4)\\ 
4\cdot1 & 4\cdot1
\end{pmatrix} = \begin{pmatrix}
8 & -16\\ 
4 & 4
\end{pmatrix}$

$3A-2B+4C = \begin{pmatrix}
3 & 21\\ 
9 & -18
\end{pmatrix} + \begin{pmatrix}
0 & -10\\ 
-4 & 2
\end{pmatrix} + \begin{pmatrix}
8 & -16\\ 
4 & 4
\end{pmatrix} = \begin{pmatrix}
3 + 0 + 8 & 21 - 10 -16\\ 
9 - 4 + 4 & -18 +2 + 4
\end{pmatrix} = \begin{pmatrix}
11 & -5\\ 
9 & -12
\end{pmatrix}$

In [23]:
# проверка
A = np.array([[1, 7], [3, -6]])
A

array([[ 1,  7],
       [ 3, -6]])

In [24]:
B = np.array([[0, 5], [2, -1]])
B

array([[ 0,  5],
       [ 2, -1]])

In [25]:
C = np.array([[2, -4], [1, 1]])
C

array([[ 2, -4],
       [ 1,  1]])

In [26]:
3 * A - 2 * B + 4 * C

array([[ 11,  -5],
       [  9, -12]])

__4.__ **Дана матрица $A=\begin{pmatrix}
4 & 1\\ 
5 & -2\\ 
2 & 3
\end{pmatrix}$.
Вычислить $AA^{T}$ и $A^{T}A$.**

Вручную:  
$A=\begin{pmatrix}
4 & 1\\ 
5 & -2\\ 
2 & 3
\end{pmatrix}$

${A}^{T}={\begin{pmatrix}
4 & 1\\ 
5 & -2\\ 
2 & 3
\end{pmatrix}}^{T} = \begin{pmatrix}
4 & 5 & 2\\ 
1 & -2 & 3
\end{pmatrix}$

$A{A}^{T} = \begin{pmatrix}
4 & 1\\ 
5 & -2\\ 
2 & 3
\end{pmatrix} \cdot \begin{pmatrix}
4 & 5 & 2\\ 
1 & -2 & 3
\end{pmatrix} = \begin{pmatrix}
4 \cdot 4 + 1 \cdot 1 & 4 \cdot 5 + 1 \cdot (-2) & 4 \cdot 2 + 1 \cdot 3\\ 
5 \cdot 4 + (-2) \cdot 1 & 5 \cdot 5 + (-2) \cdot (-2) & 5 \cdot 2 + (-2) \cdot 3\\
2 \cdot 4 + 3 \cdot 1 & 2 \cdot 5 + 3 \cdot (-2) & 2\cdot 2 + 3 \cdot 3
\end{pmatrix} = \begin{pmatrix}
17 & 18 & 11\\ 
18 & 29 & 4\\ 
11 & 4 & 13
\end{pmatrix}$

${A}^{T}A = \begin{pmatrix}
4 & 5 & 2\\ 
1 & -2 & 3
\end{pmatrix} \cdot \begin{pmatrix}
4 & 1\\ 
5 & -2\\ 
2 & 3
\end{pmatrix} = \begin{pmatrix}
4 \cdot 4 + 5 \cdot 5 + 2 \cdot 2 & 4 \cdot 1 + 5 \cdot (-2) + 2 \cdot 3\\ 
1 \cdot 4 + (-2) \cdot 5 + 3 \cdot 2 & 1 \cdot 1 + (-2) \cdot (-2) + 3 \cdot 3
\end{pmatrix} = \begin{pmatrix}
45 & 0\\ 
0 & 14
\end{pmatrix}$

In [27]:
# проверка
A = np.array([[4, 1], [5, -2], [2, 3]])
A

array([[ 4,  1],
       [ 5, -2],
       [ 2,  3]])

In [28]:
A.T

array([[ 4,  5,  2],
       [ 1, -2,  3]])

In [29]:
np.dot(A, A.T)

array([[17, 18, 11],
       [18, 29,  4],
       [11,  4, 13]])

In [30]:
np.dot(A.T, A)

array([[45,  0],
       [ 0, 14]])

__5*.__ **Написать на Python функцию для перемножения двух произвольных матриц, не используя NumPy.**

In [31]:
# Функция для перемножения двух произвольных матриц
def matrix_mult(one, another):
    if (one.shape[1] != another.shape[0]):
        return"Ошибка! Количество столбцов в первой матрице и количество строк во второй матрице должны совпадать!"
    
    Z = np.zeros((one.shape[0], another.shape[1]))
    
    for i in range(len(Z)):
        for j in range(len(Z[i])):
            cell_sum = 0
            for n in range(len(one[i])):
                cell_sum += one[i, n] * another[n, j]
            Z[i, j] = cell_sum
    return Z

In [32]:
# проверка
A = np.arange(1, 13).reshape((-1, 3))
A

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [33]:
np.random.seed(42)

In [34]:
B = np.random.randint(20, size=18).reshape((3, -1))
B

array([[ 6, 19, 14, 10,  7,  6],
       [18, 10, 10,  3,  7,  2],
       [ 1, 11,  5,  1,  0, 11]])

In [35]:
# перемножение матриц используя модуль numpy (для сравнения результатов)
np.dot(A, B)

array([[ 45,  72,  49,  19,  21,  43],
       [120, 192, 136,  61,  63, 100],
       [195, 312, 223, 103, 105, 157],
       [270, 432, 310, 145, 147, 214]])

In [36]:
# перемножение матриц по моему методу
matrix_mult(A, B)

array([[ 45.,  72.,  49.,  19.,  21.,  43.],
       [120., 192., 136.,  61.,  63., 100.],
       [195., 312., 223., 103., 105., 157.],
       [270., 432., 310., 145., 147., 214.]])

In [37]:
# неподходящие матрцы перемножаться не будут
matrix_mult(B, A)

'Ошибка! Количество столбцов в первой матрице и количество строк во второй матрице должны совпадать!'

## Практическое задание к уроку "Урок 2. Матрицы и матричные операции. Часть 2"

Все задания рекомендуется выполнять вручную, затем проверяя полученные результаты с использованием Numpy.

__1.__ **Вычислить определитель:  
a)$$\begin{vmatrix}
sinx & -cosx\\ 
cosx & sinx\\
\end{vmatrix};$$**

Вручную:  
$detA = \begin{vmatrix}
sinx & -cosx\\ 
cosx & sinx\\
\end{vmatrix} = sin(x) \cdot sin(x) - (-cos(x)) \cdot cos(x) = sin^2(x) + cos^2(x)$

In [38]:
x = Symbol('x')

In [39]:
# проверка
A = Matrix([[sin(x), -cos(x)], 
            [cos(x), sin(x)]])
A

Matrix([
[sin(x), -cos(x)],
[cos(x),  sin(x)]])

In [40]:
A.det()

sin(x)**2 + cos(x)**2

__1.__ **Вычислить определитель:  
б)$$\begin{vmatrix}
4 & 2 & 3\\ 
0 & 5 & 1\\ 
0 & 0 & 9
\end{vmatrix};$$**

Вручную (понижение порядка матрицы по последней строке):  
$detB = \begin{vmatrix}
4 & 2 & 3\\ 
0 & 5 & 1\\ 
0 & 0 & 9\\
\end{vmatrix} = 0 \cdot\begin{vmatrix}
2 & 3\\ 
5 & 1\\
\end{vmatrix} - 0 \cdot\begin{vmatrix}
4 & 3\\ 
0 & 1\\
\end{vmatrix} + 9 \cdot\begin{vmatrix}
4 & 2\\ 
0 & 5\\
\end{vmatrix} = 0 - 0 + 9\cdot(2 \cdot 5 - 2 \cdot 0) = 9 \cdot 20 = 180$

In [41]:
B = np.array([[4, 2, 3], 
            [0, 5, 1],
            [0, 0, 9]])
B

array([[4, 2, 3],
       [0, 5, 1],
       [0, 0, 9]])

In [42]:
# проверка
linalg.det(B)

180.0

__1.__ **Вычислить определитель:  
в)$$\begin{vmatrix}
1 & 2 & 3\\ 
4 & 5 & 6\\ 
7 & 8 & 9
\end{vmatrix}.$$**

Вручную (понижение порядка матрицы по первой строке):  
$detC = \begin{vmatrix}
1 & 2 & 3\\ 
4 & 5 & 6\\ 
7 & 8 & 9\\
\end{vmatrix} = 1 \cdot\begin{vmatrix}
5 & 6\\ 
8 & 9\\
\end{vmatrix} - 2 \cdot\begin{vmatrix}
4 & 6\\ 
7 & 9\\
\end{vmatrix} + 3 \cdot\begin{vmatrix}
4 & 5\\ 
7 & 8\\
\end{vmatrix} = 5\cdot9 - 6\cdot8 - 2\cdot(4\cdot9 - 6\cdot7) + 3\cdot(4\cdot8 - 5\cdot7) = 45 - 48 - 2\cdot(36 - 42) + 3\cdot(32 - 35) = -3 + 12 - 9 = 0$

In [43]:
C = np.arange(1, 10).reshape(3, 3)
C

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [44]:
linalg.det(C)

6.66133814775094e-16

__2.__ **Определитель матрицы $A$ равен $4$. Найти:  
а) $det(A^{2})$;  
б) $det(A^{T})$;  
в) $det(2A)$.**

In [45]:
det_A = 4

Используя свойства определителя матрицыи матрицы:  
**а)** возведение квадратной матрицы в квадрат - это умножение матрицы саму на себя: $A \cdot A$, значит:  
$det(A^2) = det(A\cdot A)$.  
Для двух квадратных матриц определитель их произведения равен произведению их определителей, значит:  
$det(A\cdot A) = det(A) \cdot det(A) = {det(A)}^2$

In [46]:
# det(A**2)
det_A_2 = det_A**2
det_A_2

16

Используя свойства определителя:  
**б)** определитель транспонированной матрицы равен определителю исходной.

In [47]:
# det(A_T)
det_A_T = det_A
det_A_T

4

Используя свойства определителя:  
**в)** Если квадратная матрица n-ого порядка умножается на некоторое ненулевое число, то определитель полученной матрицы равен произведению определителя исходной матрицы на это число в n-ой степени.

In [48]:
# n - порядок матрицы A
n = Symbol('n')

In [49]:
# det(2A)
det_2A = (2**n)*det_A
det_2A

4*2**n

In [50]:
# Пример
D = Matrix([[4, 2, 3], 
            [0, 5, 1],
            [5, 0, 9]])
D

Matrix([
[4, 2, 3],
[0, 5, 1],
[5, 0, 9]])

In [51]:
det_D = D.det()
det_D

115

In [52]:
D.T

Matrix([
[4, 0, 5],
[2, 5, 0],
[3, 1, 9]])

In [53]:
det_D

115

In [54]:
# проверка
D.T.det()

115

In [55]:
D**2

Matrix([
[31, 18, 41],
[ 5, 25, 14],
[65, 10, 96]])

In [56]:
det_D**2

13225

In [57]:
# проверка
(D**2).det()

13225

In [58]:
2*D

Matrix([
[ 8,  4,  6],
[ 0, 10,  2],
[10,  0, 18]])

In [59]:
n = D.shape[0]
n

3

In [60]:
(2**n) * det_D

920

In [61]:
# проверка
(2*D).det()

920

__3.__ **Доказать, что матрица  
$$\begin{pmatrix}
-2 & 7 & -3\\ 
4 & -14 & 6\\ 
-3 & 7 & 13
\end{pmatrix}$$  
вырожденная.**

Вручную:  
$detH = \begin{vmatrix}
-2 & 7 & -3\\ 
4 & -14 & 6\\ 
-3 & 7 & 13\\
\end{vmatrix}$  
Прибавим первую строку, умноженную на 2 (-4 14 6), ко второй строке (4 -14 6), по свойству определителя определитель не изменится:  
$detH = \begin{vmatrix}
-2 & 7 & -3\\ 
0 & 0 & 0\\ 
-3 & 7 & 13\\
\end{vmatrix}$  
Так как одна из строк матрицы заполнена нулями, то по свойству определителя определитель будет равен 0. Если определитель равен 0, то матрица считается вырожденной, что и требовалось доказать.

In [62]:
# проверка
H = Matrix([[-2, 7, -3],
             [4, -14, 6],
             [-3, 7, 13]])

In [63]:
H.det()

0

__4.__ **Найти ранг матрицы:  
а) $\begin{pmatrix}
1 & 2 & 3\\ 
1 & 1 & 1\\ 
2 & 3 & 4
\end{pmatrix};$**

Вручную:  
Для определения ранга можно определить количество независимых строк в матрице:  
$\begin{pmatrix}
1 & 2 & 3\\ 
1 & 1 & 1\\ 
2 & 3 & 4
\end{pmatrix}$  
Третья строка является суммой первой и второй строки.  
$\begin{pmatrix}
1 & 2 & 3\\ 
1 & 1 & 1\\ 
0 & 0 & 0
\end{pmatrix}$  
Если прибавить умноженную на -1 вторую строку (-1 -1 -1) ко второй (1 2 3), получится:  
$\begin{pmatrix}
0 & 1 & 2\\ 
1 & 1 & 1\\ 
0 & 0 & 0
\end{pmatrix}$  
Первая и вторая строка - линейно независимы, таким образом, ранг матрицы равен 2.

In [64]:
# проверка
I = Matrix([[1, 2, 3],
            [1, 1, 1],
            [2, 3, 4]])
I

Matrix([
[1, 2, 3],
[1, 1, 1],
[2, 3, 4]])

In [65]:
I.rank()

2

__4.__ **Найти ранг матрицы:  
б) $\begin{pmatrix}
0 & 0 & 2 & 1\\ 
0 & 0 & 2 & 2\\ 
0 & 0 & 4 & 3\\ 
2 & 3 & 5 & 6
\end{pmatrix}.$**

Вручную:  
Для определения ранга можно определить количество независимых строк в матрице:  
$\begin{pmatrix}
0 & 0 & 2 & 1\\ 
0 & 0 & 2 & 2\\ 
0 & 0 & 4 & 3\\ 
2 & 3 & 5 & 6
\end{pmatrix}$  
Третья строка является суммой первой и второй строки.  
$\begin{pmatrix}
0 & 0 & 2 & 1\\ 
0 & 0 & 2 & 2\\ 
0 & 0 & 0 & 0\\ 
2 & 3 & 5 & 6
\end{pmatrix}$  
Если прибавить умноженную на -1 первую строку (0 0 -2 -1) ко второй строке (0 0 2 2):  
$\begin{pmatrix}
0 & 0 & 2 & 1\\ 
0 & 0 & 0 & 1\\ 
0 & 0 & 0 & 0\\ 
2 & 3 & 5 & 6
\end{pmatrix}$  
Если прибавить умноженную на -2 первую строку (0 0 -4 -2) к четвёртой (2 3 5 6):  
$\begin{pmatrix}
0 & 0 & 2 & 1\\ 
0 & 0 & 0 & 1\\ 
0 & 0 & 0 & 0\\ 
2 & 3 & 1 & 4
\end{pmatrix}$  
Дальнейшие преобразования не имеют смысла. Первая, вторая и четвёртая строка - линейно независимы, таким образом, ранг матрицы равен 3.

In [66]:
# проверка
J = Matrix([[0, 0, 2, 1],
            [0, 0, 2, 2],
            [0, 0, 4, 3],
            [2, 3, 5, 6]])
J

Matrix([
[0, 0, 2, 1],
[0, 0, 2, 2],
[0, 0, 4, 3],
[2, 3, 5, 6]])

In [67]:
J.rank()

3