## Практическое задание к уроку "Урок 1. Линейное пространство. Основные понятия. Часть 1"

In [1]:
from sympy import *
from math import acos, degrees
from scipy import misc
from scipy import linalg
import numpy as np
from numpy.linalg import norm
from IPython.display import display

**__1.__ Исследовать на линейную зависимость:
$$f_{1}(x)=e^{x}, f_{2}(x)=1, f_{3}(x)=x+1, f_{4}(x)=x-e^{x}.$$**

In [2]:
x = Symbol('x')

In [3]:
f1 = exp(x)
f2 = 1
f3 = x + 1
f4 = x - exp(x)

Если необходимо исследовать на линейную зависимость систему функций, то необходимо составить определитель Вронского.

In [4]:
A = Matrix([[f1, f2, f3, f4],
    [diff(f1), diff(f2), diff(f3), diff(f4)],
    [diff(f1, x, x), diff(f2, x, x), diff(f3, x, x), diff(f4, x, x)],
    [diff(f1, x, x, x), diff(f2, x, x, x), diff(f3, x, x, x), diff(f4, x, x, x)]])
A

Matrix([
[exp(x), 1, x + 1, x - exp(x)],
[exp(x), 0,     1, 1 - exp(x)],
[exp(x), 0,     0,    -exp(x)],
[exp(x), 0,     0,    -exp(x)]])

In [5]:
A.det()

0

Так как определитель Вронского равен 0, то данная система функций линейно зависима.

**__2.__ Исследовать на линейную зависимость:
$$f_{1}(x)=2, f_{2}(x)=x, f_{3}(x)=x^{2}, f_{4}(x)=(x+1)^{2}.$$**

In [6]:
f1 = 2
f2 = x
f3 = x**2
f4 = (x + 1)**2

In [7]:
# Если необходимо исследовать на линейную зависимость систему функций, то необходимо составить определитель Вронского.
B = Matrix([[f1, f2, f3, f4],
    [diff(f1), diff(f2), diff(f3), diff(f4)],
    [diff(f1, x, x), diff(f2, x, x), diff(f3, x, x), diff(f4, x, x)],
    [diff(f1, x, x, x), diff(f2, x, x, x), diff(f3, x, x, x), diff(f4, x, x, x)]])
B

Matrix([
[2, x, x**2, (x + 1)**2],
[0, 1,  2*x,    2*x + 2],
[0, 0,    2,          2],
[0, 0,    0,          0]])

In [8]:
B.det()

0

Так как определитель Вронского равен 0, то данная система функций линейно зависима.

**__3.__ Найти координаты вектора $x = (2, 3, 5)\in \mathbb{R}^{3}$ в базисе $b_{1}=(0, 0, 10)$, $b_{2}=(2, 0, 0)$, $b_{3}=(0, 1, 0)$.**

In [9]:
x = np.array([2, 3, 5])
x

array([2, 3, 5])

In [10]:
b1 = np.array([0, 0, 10])
b1

array([ 0,  0, 10])

In [11]:
b2 = np.array([2, 0, 0])
b2

array([2, 0, 0])

In [12]:
b3 = np.array([0, 1, 0])
b3

array([0, 1, 0])

In [13]:
x = np.reshape(x, (-1, 1))
x

array([[2],
       [3],
       [5]])

In [14]:
b1 = np.reshape(b1, (-1, 1))
b1

array([[ 0],
       [ 0],
       [10]])

In [15]:
b2 = np.reshape(b2, (-1, 1))
b2

array([[2],
       [0],
       [0]])

In [16]:
b3 = np.reshape(b3, (-1, 1))
b3

array([[0],
       [1],
       [0]])

In [17]:
C = np.hstack((b1, b2, b3))
C

array([[ 0,  2,  0],
       [ 0,  0,  1],
       [10,  0,  0]])

In [18]:
Δ = round(np.linalg.det(C), 2)
Δ

20.0

In [19]:
Δ = Matrix(C).det()
Δ

20

Видим, что ранг матрицы С равен трем. Так как определитель не равен 0, векторы b1, b2, b3 линейно независимы, а поэтому могут быть приняты в качестве базиса пространства $\mathbb{R}^{3}$.

In [20]:
C1 = np.hstack((x, b2, b3))
C1

array([[2, 2, 0],
       [3, 0, 1],
       [5, 0, 0]])

In [21]:
Δ1 = Matrix(C1).det()
Δ1

10

In [22]:
C2 = np.hstack((b1, x, b3))
C2

array([[ 0,  2,  0],
       [ 0,  3,  1],
       [10,  5,  0]])

In [23]:
Δ2 = Matrix(C2).det()
Δ2

20

In [24]:
C3 = np.hstack((b1, b2, x))
C3

array([[ 0,  2,  2],
       [ 0,  0,  3],
       [10,  0,  5]])

In [25]:
Δ3 = Matrix(C3).det()
Δ3

60

In [26]:
x1 = Δ1/Δ
x1

1/2

In [27]:
x2 = Δ2/Δ
x2

1

In [28]:
x3 = Δ3/Δ
x3

3

Разложение вектора в базисе b1, b2, b3:  
$\vec{x} = 1/2 \cdot \vec{b1} + 1 \cdot \vec{b2} + 3 \cdot \vec{b3}$

Координаты вектора в базисе b1, b2, b3:

In [29]:
X = np.array([x1, x2, x3])
X

array([1/2, 1, 3], dtype=object)

**__4.__ Найти координаты вектора $3x^{2}-2x+2\in\mathbb{R}^{3}[x]$:  
а) в базисе $1$, $x$, $x^{2}$.**

In [30]:
x = Symbol('x')

In [31]:
a1 = 1
a2 = x
a3 = x**2

In [32]:
A = Matrix([[a1, a2, a3],
    [diff(f1), diff(f2), diff(f3)],
    [diff(f1, x, x), diff(f2, x, x), diff(f3, x, x)]])
A

Matrix([
[1, x, x**2],
[0, 1,  2*x],
[0, 0,    2]])

In [33]:
Δ = A.det()
Δ

2

Видим, что ранг матрицы A равен трем. Так как определитель не равен 0, система функций $1, x, {x}^{2}$ линейно независима и может быть принята в качестве базиса $\mathbb{R}^{3}[x]$.

In [34]:
X = 3*x**2 - 2*x + 2
X

3*x**2 - 2*x + 2

Нужно привести выражение к виду $x1 \cdot \vec{a1} + x2 \cdot \vec{a2} + x3 \cdot \vec{a3}$:  
$X = 2 \cdot 1 + (- 2) \cdot x + 3 \cdot {x}^{2}$

In [35]:
x1 = 2
x2 = -2
x3 = 3

In [36]:
# Координаты вектора:
X = np.array([x1, x2, x3])
X

array([ 2, -2,  3])

**__4.__ Найти координаты вектора $3x^{2}-2x+2\in\mathbb{R}^{3}[x]$:  
б) в базисе $x^{2}$, $x-1$, $1$.**

In [37]:
b1 = x**2
b2 = x - 1
b3 = 1

In [38]:
B = Matrix([[b1, b2, b3],
    [diff(f1), diff(f2), diff(f3)],
    [diff(f1, x, x), diff(f2, x, x), diff(f3, x, x)]])
B

Matrix([
[x**2, x - 1,   1],
[   0,     1, 2*x],
[   0,     0,   2]])

In [39]:
B.det()

2*x**2

Видим, что ранг матрицы B равен трем. Так как определитель не равен 0, система функций ${x}^{2}, x - 1, 1$ линейно независима и может быть принята в качестве базиса $\mathbb{R}^{3}[x]$.

In [40]:
X = 3*x**2 - 2*x + 2
X

3*x**2 - 2*x + 2

Нужно привести выражение к виду $x1 \cdot \vec{b1} + x2 \cdot \vec{b2} + x3 \cdot \vec{b3}$:  
$X = 3 \cdot {x}^{2} - 2x + 2 $  
$X = 3 \cdot {x}^{2} + (-2) \cdot (x - 1) + 0 \cdot 1 $

In [41]:
x1 = 3
x2 = -2
x3 = 0

Координаты вектора $3x^{2}-2x+2\in\mathbb{R}^{3}[x]$ в базисе $x^{2}$, $x-1$, $1$:

In [42]:
X = np.array([x1, x2, x3])
X

array([ 3, -2,  0])

**__5.__ Установить, является ли линейным подпространством:  
а) совокупность всех векторов трехмерного пространства, у которых по крайней мере одна из первых двух координат равна нулю.**

Чтобы доказать, что подпространство L1, состоящее из элементов, у которых по крайней мере одна из первых двух координат равна нулю, является линейным подпространством, необходимо доказать, что это подпространство является линейным и удовлетворяет восьми условиям определения линейного пространства.

Операция сложения векторов должна удовлетворять следующим условиям:  
1) коммутативность:  u + v = v + u ;  
2) ассоциативность:  (u + v) + w = u + (v + w) ;  
3) существование такого элемента  0 ∈ L1 , что  u + 0 = u  для любого  u ;  
4) существование для любого  u∈V  такого вектора  −u ∈ L1 , что  u + (−u) = 0 .  
  
Операция умножения вектора на скаляр должна подчиняться следующим условиям:  
5)  1 ⋅ u = u  для любого  u ∈ L1 ;  
6) ассоциативность операции умножения на скаляр:  λ(μ ⋅ u) = (λ ⋅ μ)u ;  
7) дистрибутивность относительно сложения векторов:  λ(u + v) = λu + λv ;  
8) дистрибутивность относительно сложения скаляров:  (λ + μ)u = λu + μu .

Необходимо доказать, что любые вектора $u + v \in L1$ и $\alpha \cdot u \in L1$

In [43]:
x = Symbol('x')
y = Symbol('y')
z = Symbol('z')

In [44]:
def comparison(one, another):
    display(simplify(one))
    print('==')
    display(simplify(another), simplify(one) == simplify(another))

Выберем произвольные вектора из подмножества:

In [45]:
u = Array([0, 0, x])
u

[0, 0, x]

In [46]:
v = Array([x, 0, y])
v

[x, 0, y]

In [47]:
w = Array([0, y, z])
w

[0, y, z]

In [48]:
# 1) коммутативность
comparison(u + v, v + u)

[x, 0, x + y]

==


[x, 0, x + y]

True

In [49]:
# 2) ассоциативность
comparison((u + v) + w, u + (v + w))

[x, y, x + y + z]

==


[x, y, x + y + z]

True

Результат последнего выражения не принадлежит подмножеству L1. Подмножество L1 не является линейным подмножеством.

**__5__. Установить, является ли линейным подпространством:  
б) все векторы, являющиеся линейными комбинациями данных векторов $\{u_{1}, u_{2}, ..., u_{n}\}$.**

_Линейным (векторным) пространством_ $\mathit{V}$ над некоторым полем $K$ называется множество элементов, называемых векторами, с заданными на нем операциями

- сложения: $V \times V \rightarrow V$ (любым двум элементам $u$ и $v$ множества $V$ ставится в соответствие третий элемент $w$ этого же множества, называемый _суммой_ элементов $u$ и $v$ и обозначаемый $w=u+v$);

- умножения на число: $K \times V \rightarrow V$ (любому элементу $u$ множества $V$ и любому вещественному числу $\lambda$ ставится в соответствие элемент $x$ этого же множества, называемый _произведением элемента $u$ на число_ $\lambda$ и обозначаемый $x=\lambda u$ или $x=u\lambda$).

По определению линейные комбинации векторов, принадлежащих линейному (векторному) пространству, точнее их результат, принадлежат тому же линейному пространству. Таким образом, все векторы, являющиеся линейными комбинациями данных векторов $\{u_{1}, u_{2}, ..., u_{n}\}$, являются линейным подпространством линейного пространства, которому принадлежат данные векторы.

## Практическое задание к уроку "Урок 1. Линейное пространство. Основные понятия. Часть 2"

**__1.__ Найти скалярное произведение векторов $x, y \in \mathbb{R}$:<br>
а) $x=(0,-3, 6),~y=(-4, 7, 9).$**

In [50]:
x = np.array([0, -3, 6])

In [51]:
y = np.array([-4, 7, 9])

In [52]:
# скалярное произведение
x.dot(y)

33

**__1.__ Найти скалярное произведение векторов $x, y \in \mathbb{R}$:<br>
б) $x=(7, -4, 0, 1),~y=(-3, 1, 11, 2).$**

In [53]:
x = np.array([7, -4, 0, 1])
x

array([ 7, -4,  0,  1])

In [54]:
y = np.array([-3, 1, 11, 2])
y

array([-3,  1, 11,  2])

In [55]:
# скалярное произведение
x.dot(y)

-23

**__2.__ Найти нормы векторов $(4, 2, 4)$ и $(12, 3, 4)$ и угол между ними.**

In [56]:
x = np.array([4, 2, 4])
x

array([4, 2, 4])

In [57]:
y = np.array([12, 3, 4])
y

array([12,  3,  4])

In [58]:
# Манхэттенская норма векторов
x_manh = norm(x, ord=1)
x_manh

10.0

In [59]:
y_manh = norm(y, ord=1)
y_manh

19.0

In [60]:
# Евклидова норма векторов
x_evcl = norm(x, ord=2)
x_evcl

6.0

In [61]:
y_evcl = norm(y, ord=2)
y_evcl

13.0

Косинус угла между векторами равен скалярному произведению векторов, поделенному на произведение модулей векторов. Длина вектора |a| в прямоугольных декартовых координатах равна квадратному корню из суммы квадратов его координат. 

In [62]:
# длина вектора x
x_l = sqrt(x.dot(x))
x_l

6

In [63]:
# длина вектора y
y_l = sqrt(y.dot(y))
y_l

13

In [64]:
# скалярное произведение векторов
x_y = x.dot(y)
x_y

70

In [65]:
# косинус угла между векторами x и y
cos_γ = x_y / (x_l * y_l)
cos_γ

35/39

In [66]:
# угол между векторами x и y в радианах и в градусах
γ =  acos(cos_γ)
print(γ, degrees(γ))

0.45687400353266105 26.176952171666542


**__3.__ Будет ли линейное пространство евклидовым, если за скалярное произведение принять:<br>
а) произведение длин векторов?**

Вещественное линейное пространство E называется евклидовым пространством, если каждой упорядоченной паре элементов x и y из этого пространства поставлено в соответствие вещественное число (x, y), называемое скалярным произведением, так, что выполнены аксиомы:  
1\. ∀ x, y ∈ E, (x, y) = (y, x) ;  
2\. ∀ x, y ∈ E, λ ∈ R, (λx, y) = λ(x,y) ;  
3\. ∀ $x_1$, $x_2$, y ∈ E, ($x_1$ + $x_2$, y) = ($x_1$, y) + ($x_2$, y) ;  
4\. ∀ x ∈ E, x ≠ o, (x, x) > 0 .

In [67]:
x1 = Symbol('x1')
x2 = Symbol('x2')
x3 = Symbol('x3')
y1 = Symbol('y1')
y2 = Symbol('y2')
y3 = Symbol('y3')
z1 = Symbol('z1')
z2 = Symbol('z2')
z3 = Symbol('z3')

In [68]:
np.random.seed(45)

In [69]:
x = Matrix([x1, x2, x3])
x

Matrix([
[x1],
[x2],
[x3]])

In [70]:
x_l = sqrt(x.dot(x))
x_l

sqrt(x1**2 + x2**2 + x3**2)

In [71]:
y = Matrix([y1, y2, y3])
y

Matrix([
[y1],
[y2],
[y3]])

In [72]:
y_l = sqrt(y.dot(y))
y_l

sqrt(y1**2 + y2**2 + y3**2)

In [73]:
# проверим, соответствуют ли условия условиям определения евклидова пространства
# 1. (𝑥,𝑦)=(𝑦,𝑥)
comparison(x_l*y_l, y_l*x_l)

sqrt(x1**2 + x2**2 + x3**2)*sqrt(y1**2 + y2**2 + y3**2)

==


sqrt(x1**2 + x2**2 + x3**2)*sqrt(y1**2 + y2**2 + y3**2)

True

In [74]:
a = Symbol('a')
λ = a

In [75]:
x_λ_l = sqrt((λ * x).dot(λ * x))
x_λ_l

sqrt(a**2*x1**2 + a**2*x2**2 + a**2*x3**2)

In [76]:
x_λ_l*y_l

sqrt(y1**2 + y2**2 + y3**2)*sqrt(a**2*x1**2 + a**2*x2**2 + a**2*x3**2)

In [77]:
λ * x_l*y_l

a*sqrt(x1**2 + x2**2 + x3**2)*sqrt(y1**2 + y2**2 + y3**2)

In [78]:
# 2. (λ𝑥,𝑦)=λ(𝑥,𝑦)
display(simplify(x_λ_l*y_l), λ * x_l*y_l)

sqrt(a**2*(x1**2 + x2**2 + x3**2))*sqrt(y1**2 + y2**2 + y3**2)

a*sqrt(x1**2 + x2**2 + x3**2)*sqrt(y1**2 + y2**2 + y3**2)

In [79]:
# Если внести a под знак корня с переменными x, то выражения будут равны

In [80]:
z = Matrix([z1, z2, z3])
z

Matrix([
[z1],
[z2],
[z3]])

In [81]:
z_l = sqrt(z.dot(z))
z_l

sqrt(z1**2 + z2**2 + z3**2)

In [82]:
x_z_l = sqrt((x+z).dot(x+z))
x_z_l

sqrt((x1 + z1)**2 + (x2 + z2)**2 + (x3 + z3)**2)

In [83]:
# 3. (𝑥1+𝑥2,𝑦)=(𝑥1,𝑦)+(𝑥2,𝑦)
comparison(x_z_l*y_l, simplify(x_l * y_l + z_l*y_l))

sqrt(y1**2 + y2**2 + y3**2)*sqrt((x1 + z1)**2 + (x2 + z2)**2 + (x3 + z3)**2)

==


(sqrt(x1**2 + x2**2 + x3**2) + sqrt(z1**2 + z2**2 + z3**2))*sqrt(y1**2 + y2**2 + y3**2)

False

Если за скалярное произведение принять произведение длин векторов, то такое пространство не будет евклидовым, так как не выполняется третья аксиома. 

**__3.__ Будет ли линейное пространство евклидовым, если за скалярное произведение принять:<br>
б) утроенное обычное скалярное произведение векторов?**

Вещественное линейное пространство E называется евклидовым пространством, если каждой упорядоченной паре элементов x и y из этого пространства поставлено в соответствие вещественное число (x, y), называемое скалярным произведением, так, что выполнены аксиомы:  
1\. ∀ x, y ∈ E, 3(x, y) = 3(y, x) ;  
2\. ∀ x, y ∈ E, λ ∈ R, 3(λx, y) = 3λ(x,y) ;  
3\. ∀ $x_1$, $x_2$, y ∈ E, 3($x_1$ + $x_2$, y) = 3($x_1$, y) + 3($x_2$, y) ;  
4\. ∀ x ∈ E, x ≠ o, 3(x, x) > 0 .

Аксиомы выполняются, следовательно, если за скалярное произведение принять утроенное обычное скалярное произведение векторов, то линейное пространство будет евклидовым.

**__4.__ Какие из нижеперечисленных векторов образуют ортонормированный базис в линейном пространстве $\mathbb{R}^{3}$:  
а) $(1,0,0),(0,0,1);$  
б) $(1/\sqrt{2},-1/\sqrt{2},0),(1/\sqrt{2},1/\sqrt{2},0), (0,0,1);$  
в) $(1/2, -1/2, 0), (0, 1/2, 1/2), (0,0,1);$  
г) $(1,0,0),(0,1,0),(0,0,1)?$**

В конечномерном евклидовом пространстве базис $\{e1, e2, ..., en\}$ называется ортонормированным, если (ei, ej) =  0 ∀ i ≠ j и (ei, ei) = 1 ∀ i ∈ $[1, n]$.  
Ортонормированный базис является ортогональным и состоит из векторов единичной длины.

**а) $(1,0,0),(0,0,1)$**  
Базис плоскости - 3, судя по координатам, векторов - 2, в любом случае 2 вектора не могут быть базисом для 3-мерного пространства.

**б) $(1/\sqrt{2},-1/\sqrt{2},0),(1/\sqrt{2},1/\sqrt{2},0), (0,0,1)$**

In [84]:
b1 = np.array([1/sqrt(2), -1/sqrt(2), 0])
b1

array([sqrt(2)/2, -sqrt(2)/2, 0], dtype=object)

In [85]:
b2 = np.array([1/sqrt(2), 1/sqrt(2), 0])
b2

array([sqrt(2)/2, sqrt(2)/2, 0], dtype=object)

In [86]:
b3 = np.array([0, 0, 1])
b3

array([0, 0, 1])

In [87]:
b1.dot(b2)

0

In [88]:
b1.dot(b3)

0

In [89]:
b2.dot(b3)

0

In [90]:
round(b1.dot(b1), 2)

1.0

In [91]:
round(b2.dot(b2), 2)

1.0

In [92]:
round(b3.dot(b3), 2)

1

Векторы $(1/\sqrt{2},-1/\sqrt{2},0),(1/\sqrt{2},1/\sqrt{2},0), (0,0,1)$ образуют ортонормированный базис в линейном пространстве $\mathbb{R}^{3}$.

**в) $(1/2, -1/2, 0), (0, 1/2, 1/2), (0,0,1)$**

In [93]:
c1 = np.array([1/2, -1/2, 0])
c1

array([ 0.5, -0.5,  0. ])

In [94]:
c2 = np.array([0, 1/2, 1/2])
c2

array([0. , 0.5, 0.5])

In [95]:
c3 = np.array([0, 0, 1])
c3

array([0, 0, 1])

In [96]:
c1.dot(c2)

-0.25

Векторы $(1/2, -1/2, 0), (0, 1/2, 1/2), (0,0,1)$ не удовлетворяют (ei, ej) =  0$ $∀ i ≠ j.

**г) $(1,0,0),(0,1,0),(0,0,1)$**

In [97]:
d1 = np.array([1, 0, 0])
d1

array([1, 0, 0])

In [98]:
d2 = np.array([0, 1, 0])
d2

array([0, 1, 0])

In [99]:
d3 = np.array([0, 0, 1])
d3

array([0, 0, 1])

In [100]:
d1.dot(d2)

0

In [101]:
d1.dot(d3)

0

In [102]:
d2.dot(d3)

0

In [103]:
d1.dot(d1)

1

In [104]:
d2.dot(d2)

1

In [105]:
d3.dot(d3)

1

Векторы $(1,0,0),(0,1,0),(0,0,1)$ образуют ортонормированный базис в линейном пространстве $\mathbb{R}^{3}$.