## Практическое задание к уроку "Урок 4. Системы линейных уравнений. Часть 1"

In [1]:
import numpy as np
from sympy import *
from sympy.solvers.solvers import solve

**__1.__ Решить систему уравнений методом Гаусса: $\begin{cases}
x_{1}+x_{2}-x_{3}-2x_{4}=0, \\
2x_{1}+x_{2}-x_{3}+x_{4}=-2, \\
x_{1}+x_{2}-3x_{3}+x_{4}=4.
\end{cases}$**

По методу Гаусса необходимо записать систему уравнений в виде расширенной матрицы и произвести элементарные преобразования прямым ходом, пока не будет возможно выразить одну из переменных, затем методом обратного хода найти значения всех остальных переменных.
$A = \begin{pmatrix}
1 & 1 & -1 & -2 & | & 0\\ 
2 & 1 & -1 & 1 & | & -2\\ 
1 & 1 & -3 & 1 & | & 4
\end{pmatrix}$  
Прибавим к второй стоке первую, умноженную на -2 (-2 -2 2 4 | 0), и к третьей первую, умноженную на -1 (-1 -1 1 2 | 0):
$A = \begin{pmatrix}
1 & 1 & -1 & -2 & | & 0\\ 
0 & -1 & 1 & 5 & | & -2\\ 
0 & 0 & -2 & 3 & | & 4
\end{pmatrix}$  
Получится:  
$\begin{cases}
x_{1}+x_{2}-x_{3}-2x_{4}=0, \\
~~~~-x_{2}+x_{3}+5x_{4}=-2, \\
~~~~~~~~~~~-2x_{3}+3x_{4}=4.
\end{cases}$  
Бесконечное множество решений принято записывать в виде общего решения.   
Последнее уравнение содержит две неизвестных. Эти базисные неизвестные нужно выразить через свободные неизвестные. В данном случае можно рассматривать в качестве свободного параметра $x_{4}=c$. Тогда, выражая остальные переменные через $c$, получим:  
$x_{4}=c,$  
$-2x_{3} + 3с = 4 \; \Leftrightarrow \; x_{3} = {{-4 + 3с}\over{2}} \; \Leftrightarrow \; x_{3} = {{3}\over{2}}с - 2$  
$-x_{2}+{{-4 + 3с}\over{2}}+5c=-2 \; \Leftrightarrow \; -2x_{2}-4 + 3с+10c=-4 \; \Leftrightarrow \; -2x_{2}=- 13c \; \Leftrightarrow \; x_{2}={{13с}\over{2}} \; \Leftrightarrow \; x_{2}={{13}\over{2}}с$  
$x_{1}+{{13с}\over{2}}-{{-4 + 3с}\over{2}}-2с=0 \; \Leftrightarrow \; 2x_{1}+13c+4 - 3с-4с=0 \; \Leftrightarrow \; 2x_{1} = {{-4-6с}\over{2}} \; \Leftrightarrow \; 2x_{1} = -3c-2$  
Подставляя произвольные числа вместо $c$, мы получим частное решение. Например, при $c=2$:  
$x_{1}=-3*2-2 = -8$  
$x_{2}={{13 \cdot 2}\over{2}} = 13$  
$x_{3}= {{3 \cdot 2}\over{2}}-2 = 1$  
$x_{4}=2$  
Подставим значения в исходную систему:  
$\begin{cases}
x_{1}+x_{2}-x_{3}-2x_{4}=0, \\
2x_{1}+x_{2}-x_{3}+x_{4}=-2, \\
x_{1}+x_{2}-3x_{3}+x_{4}=4.
\end{cases} \; \Leftrightarrow \; \begin{cases}
-8+13-1-2\cdot2=0, \\
2\cdot(-8)+13-1+2=-2, \\
-8+13-3\cdot1+2=4.
\end{cases} \; \Leftrightarrow \; \begin{cases}
0=0, \\
-2=-2, \\
4=4.
\end{cases}$  
Параметр $c$ может принимать бесконечное количество значений, при которых уравнения в системе будут обращаться в тождества.

In [2]:
# проверка

In [3]:
x1 = Symbol('x1')
x2 = Symbol('x2')
x3 = Symbol('x3')
x4 = Symbol('x4')

In [4]:
A = Matrix([[x1, x2, -x3, -2*x4],[2*x1, x2, -x3, x4], [x1, x2, -3*x3, x4]])
A

Matrix([
[  x1, x2,   -x3, -2*x4],
[2*x1, x2,   -x3,    x4],
[  x1, x2, -3*x3,    x4]])

In [5]:
b = Matrix([0, -2, 4])
b

Matrix([
[ 0],
[-2],
[ 4]])

In [6]:
A_ = Matrix([[x1, x2, -x3, -2*x4],[0, -x2, x3, 5*x4], [0, 0, -2*x3, 3*x4]])
A_

Matrix([
[x1,  x2,   -x3, -2*x4],
[ 0, -x2,    x3,  5*x4],
[ 0,   0, -2*x3,  3*x4]])

In [7]:
# -2x_{3} + 3x_{4} = 4
a1 = -2*x3 + 3*x4 - 4

In [8]:
solve(a1)

[{x3: 3*x4/2 - 2}]

In [9]:
# -x_{2} + x_{3} + 5x_{4} = -2
a2 = -x2 + (3*x4)/2 - 2 + 5*x4 + 2

In [10]:
solve(a2)

[{x2: 13*x4/2}]

In [11]:
# x_{1} + x_{2} - x_{3} - 2x_{4} = 0
a3 = x1 + 13*x4/2 - (3*x4/2 - 2) - 2*x4

In [12]:
solve(a3)

[{x1: -3*x4 - 2}]

In [13]:
# x4 = 2
x_1 = -3*2 - 2
x_1

-8

In [14]:
x_2 = 13*2/2
x_2

13.0

In [15]:
x_3 = 3*2/2 - 2
x_3

1.0

In [16]:
x_4 = 2
x_4

2

In [17]:
A = np.array([[x_1, x_2, -x_3, -2*x_4],[2*x_1, x_2, -x_3, x_4], [x_1, x_2, -3*x_3, x_4]])
A

array([[ -8.,  13.,  -1.,  -4.],
       [-16.,  13.,  -1.,   2.],
       [ -8.,  13.,  -3.,   2.]])

In [18]:
sum(A[0])

0.0

In [19]:
sum(A[1])

-2.0

In [20]:
sum(A[2])

4.0

In [21]:
b

Matrix([
[ 0],
[-2],
[ 4]])

In [22]:
# система уравнений решена верно

**__2.__ Проверить на совместность и выяснить, сколько решений будет иметь система линейных уравнений:  
а) $\begin{cases}
3x_{1}-x_{2}+x_{3}=4, \\
2x_{1}-5x_{2}-3x_{3}=-17, \\
x_{1}+x_{2}-x_{3}=0;
\end{cases}$**

In [23]:
A = Matrix([[3, -1, 1], [2, -5, -3], [1, 1, -1]])
A

Matrix([
[3, -1,  1],
[2, -5, -3],
[1,  1, -1]])

In [24]:
b = Matrix([4, -17, 0])
b

Matrix([
[  4],
[-17],
[  0]])

In [25]:
A.det()

32

Определитель матрицы не равен 0, следовательно система совместна (матрица, обратная матрице А, существует)

In [26]:
rankA = A.rank()
rankA

3

In [27]:
A2 = A.col_insert(3, b)
A2

Matrix([
[3, -1,  1,   4],
[2, -5, -3, -17],
[1,  1, -1,   0]])

In [28]:
rankA2 = A2.rank()
rankA2

3

In [29]:
n = A.shape[1]
n

3

In [30]:
rankA == rankA2 == n

True

Ранги матрицы коэффициентов A и расширенной матрицы A2 совпадают и равны количеству неизвестных n, значит, по теореме Кронекера-Капелли, система линейных уравнений совместна и определена, то есть имеет единственное решение.

**__2.__ Проверить на совместность и выяснить, сколько решений будет иметь система линейных уравнений:  
б) $\begin{cases}
2x_{1}-4x_{2}+6x_{3}=1, \\
x_{1}-2x_{2}+3x_{3}=-2, \\
3x_{1}-6x_{2}+9x_{3}=5;
\end{cases}$**

In [31]:
A = Matrix([[2, -4, 6], [1, -2, 3], [3, -6, 9]])
A

Matrix([
[2, -4, 6],
[1, -2, 3],
[3, -6, 9]])

In [32]:
b = Matrix([1, -2, 5])
b

Matrix([
[ 1],
[-2],
[ 5]])

In [33]:
A.det()

0

Определитель матрицы равен 0, следовательно система несовместна (не имеет решений). Проверим ещё с помощью теоремы Кронекера-Капелли.

In [34]:
A2 = A.col_insert(3, b)
A2

Matrix([
[2, -4, 6,  1],
[1, -2, 3, -2],
[3, -6, 9,  5]])

In [35]:
rankA2 = A2.rank()
rankA2

2

In [36]:
rankA == rankA2

False

Ранги матрицы коэффициентов A и расширенной матрицы A2 не совпадают, значит, по теореме Кронекера-Капелли, система линейных уравнений также несовместна, то есть не имеет решений.

**__2.__ Проверить на совместность и выяснить, сколько решений будет иметь система линейных уравнений:  
в) $\begin{cases}
x_{1}+2x_{2}+5x_{3}=4, \\
3x_{1}+x_{2}-8x_{3}=-2. 
\end{cases}$**

In [37]:
A = Matrix([[1, 2, 5], [3, 1, -8]])
A

Matrix([
[1, 2,  5],
[3, 1, -8]])

Определитель посчитать не можем, так как матрица не квадратная. Для определения совместности используем теорему Кронекера-Капелли.

In [38]:
b = Matrix([4, -2])
b

Matrix([
[ 4],
[-2]])

In [39]:
rankA = A.rank()
rankA

2

In [40]:
A2 = A.col_insert(3, b)
A2

Matrix([
[1, 2,  5,  4],
[3, 1, -8, -2]])

In [41]:
rankA2 = A2.rank()
rankA2

2

In [42]:
n = A.shape[1]
n

3

In [43]:
rankA == rankA2 < n

True

Ранги матрицы коэффициентов A и расширенной матрицы A2 совпадают и меньше количества неизвестных n, значит, по теореме Кронекера-Капелли, система линейных уравнений совместна и неопределена, то есть имеет бесконечное число решение.

**__3.__ Проверить на совместность и выяснить, сколько решений будет иметь система линейных уравнений, заданная расширенной матрицей $\tilde{A}=\begin{pmatrix}
\left.\begin{matrix}
1 & 3 & -2 & 4\\ 
0 & 5 & 0 & 1\\ 
0 & 0 & 3 & 0\\ 
0 & 0 & 0 & 2
\end{matrix}\right|
\begin{matrix}
3\\ 
2\\
4\\
1
\end{matrix}
\end{pmatrix}.$**

In [44]:
A_ = Matrix([[1, 3, -2, 4, 3], [0, 5, 0, 1, 2], [0, 0, 3, 0, 4], [0, 0, 0, 2, 1]])
A_

Matrix([
[1, 3, -2, 4, 3],
[0, 5,  0, 1, 2],
[0, 0,  3, 0, 4],
[0, 0,  0, 2, 1]])

In [45]:
A = A_.copy()
A.col_del(4)
A

Matrix([
[1, 3, -2, 4],
[0, 5,  0, 1],
[0, 0,  3, 0],
[0, 0,  0, 2]])

In [46]:
rankA_ = A_.rank()
rankA_

4

In [47]:
rankA = A.rank()
rankA

4

In [48]:
n = A.shape[1]
n

4

In [49]:
rankA == rankA_ == n

True

Ранги матрицы коэффициентов A и расширенной матрицы A_ совпадают и равны количеству неизвестных n, значит, по теореме Кронекера-Капелли, система линейных уравнений совместна и определена, то есть имеет единственное решение.

**__4.__ Дана система линейных уравнений, заданная расширенной матрицей $\tilde{A}=\begin{pmatrix}
\left.\begin{matrix}
1 & 2 & 3\\ 
4 & 5 & 6\\ 
7 & 8 & 9
\end{matrix}\right|
\begin{matrix}
a\\ 
b\\
c
\end{matrix}
\end{pmatrix}.$  
Найти соотношение между параметрами $a$, $b$ и $c$, при которых система является несовместной.**

Система будет несовместной, если ранг матрицы коэффициентов будет меньше ранга расширенной матрицы, то есть, если хотя бы одна строка матрицы коэффициентов будет иметь все элементы нули, а элемент расширенной матрицы для этой строки будет не равен 0.
Попробуем таким образом упростить расширенную матрицу путём элементарных преобразований:  
$\tilde{A} = \begin{pmatrix}
1 & 2 & 3 & | & a\\ 
4 & 5 & 6 & | & b\\ 
7 & 8 & 9 & | & c
\end{pmatrix}$  
Прибавим ко второй стоке первую, умноженную на -2 (-2 -4 -6 | -2a), и к третьей первую, умноженную на -3 (-3 -6 -9 | -3a):  
$\tilde{A} = \begin{pmatrix}
1 & 2 & 3 & | & a\\ 
2 & 1 & 0 & | & b-2a\\ 
4 & 2 & 0 & | & c-3a
\end{pmatrix}$  
Прибавим к третьей строке вторую, умноженную на -2 (-4 -2 0 | -2(b-2a)):  
$\tilde{A} = \begin{pmatrix}
1 & 2 & 3 & | & a\\ 
2 & 1 & 0 & | & b-2a\\ 
0 & 0 & 0 & | & c-3a-2(b-2a))
\end{pmatrix}$  
Последняя строка обнулилась, если $c-3a-2(b-2a)) = 0$, то решения будут, система будет совместной. По заданию, нужно определить соотношение между a, b и c, при котором система будет несовместна:  
$c-3a-2(b-2a)) \neq 0$  
$c - 3a - 2b + 2a = c - a - 2b$  
$c - a - 2b \neq 0$ - соотношение между параметрами, при которых система линейных уравнений является несовместной.

## Практическое задание к уроку "Урок 4. Системы линейных уравнений. Часть 2"

**__1.__ Решить систему уравнений методом Крамера:  
а) $\begin{cases}
x_{1}-2x_{2}=1 \\
3x_{1}-4x_{2}=7
\end{cases}$**

По методу Крамера, неизвестные можно найти с помощью формулы:  
$$x_{i}=\frac{detA_{i}}{detA},$$

где $A_{i}$ — это матрица, получаемая заменой $i$-го столбца на вектор-столбец свободных членов $b$.  

$A = \begin{pmatrix}
1 & -2\\ 
3 & -4
\end{pmatrix}$  

$b = \begin{pmatrix}
1\\ 
7
\end{pmatrix}$  

$detA = \begin{vmatrix}
1 & -2\\ 
3 & -4
\end{vmatrix} = 1 \cdot (-4) - (-2) \cdot 3 = -4 + 6 = 2$  

Количество неизвестных и уравнений совпадает, определитель матрицы не равен 0, значит, систему уравнений можно решить методом Крамера.  

$detA_{1} = \begin{vmatrix}
1 & -2\\ 
7 & -4
\end{vmatrix} = 1 \cdot (-4) - (-2) \cdot 7 = -4 + 14 = 10$

$detA_{2} = \begin{vmatrix}
1 & 1\\ 
3 & 7
\end{vmatrix} = 1 \cdot 7 - 1 \cdot 3 = 7 - 3 = 4$

$x_{1}=\frac{detA_{1}}{detA} = 10/2 = 5$  
$x_{2}=\frac{detA_{2}}{detA} = 4/2 = 2$

In [50]:
# проверка

In [51]:
A = Matrix([[1, -2], [3, -4]])
A

Matrix([
[1, -2],
[3, -4]])

In [52]:
b = Matrix([1, 7])
b

Matrix([
[1],
[7]])

In [53]:
# заменяем первый столбец
A1 = A.copy()
A1.col_del(0)
A1 = A1.col_insert(0, b)
A1

Matrix([
[1, -2],
[7, -4]])

In [54]:
# заменяем второй столбец
A2 = A.copy()
A2.col_del(1)
A2 = A2.col_insert(1, b)
A2

Matrix([
[1, 1],
[3, 7]])

In [55]:
# определитель исходной матрицы
detA = A.det()
detA

2

In [56]:
# определитель матрицы с заменой первого столбца
detA1 = A1.det()
detA1

10

In [57]:
# определитель матрицы с заменой второго столбца
detA2 = A2.det()
detA2

4

In [58]:
# первое значение
x1 = detA1/detA
x1

5

In [59]:
# второе значение
x2 = detA2/detA
x2

2

In [60]:
X = Matrix([x1, x2])
X

Matrix([
[5],
[2]])

**__1.__ Решить систему уравнений методом Крамера:  
б) $\begin{cases}
2x_{1}-x_{2}+5x_{3}=10 \\
x_{1}+x_{2}-3x_{3}=-2 \\
2x_{1}+4x_{2}+x_{3}=1
\end{cases}$**

$A = \begin{pmatrix}
2 & -1 & 5\\ 
1 & 1 & -3\\ 
2 & 4 & 1
\end{pmatrix}$  

$b = \begin{pmatrix}
10\\ 
-2\\
1
\end{pmatrix}$  

Разложение по первому столбцу:
$detA = \begin{vmatrix}
2 & -1 & 5\\ 
1 & 1 & -3\\ 
2 & 4 & 1
\end{vmatrix} = 2 \cdot \begin{vmatrix}
1 & -3\\ 
4 & 1
\end{vmatrix} - 1 \cdot \begin{vmatrix}
-1 & 5\\  
4 & 1
\end{vmatrix} + 2 \cdot \begin{vmatrix}
-1 & 5\\ 
1 & -3
\end{vmatrix} = 2 \cdot (1 \cdot 1 - (-3) \cdot 1) - (-1 \cdot 1 - 5 \cdot 4) + 2 \cdot (-1 \cdot (-3) - 5 \cdot 1) = 26 + 21 - 4 = 43$  

Количество неизвестных и уравнений совпадает, определитель матрицы не равен 0, значит, систему уравнений можно решить методом Крамера.  

Разложение по последней строке:
$detA_{1} = \begin{vmatrix}
10 & -1 & 5\\ 
-2 & 1 & -3\\ 
1 & 4 & 1
\end{vmatrix} = 1 \cdot \begin{vmatrix}
-1 & 5\\ 
1 & -3
\end{vmatrix} - 4 \cdot \begin{vmatrix}
10 & 5\\ 
-2 & -3
\end{vmatrix} + 1 \cdot \begin{vmatrix}
10 & -1\\ 
-2 & 1 
\end{vmatrix} = (-1 \cdot (-3) - 5 \cdot 1) - 4 \cdot (10 \cdot (-3) - 5 \cdot (-2)) + (10 \cdot 1 - (-1) \cdot (-2)) = -2 + 80 + 8 = 86$  

Разложение по первому столбцу:
$detA_{2} = \begin{vmatrix}
2 & 10 & 5\\ 
1 & -2 & -3\\ 
2 & 1 & 1
\end{vmatrix} = 2 \cdot \begin{vmatrix}
-2 & -3\\ 
1 & 1
\end{vmatrix} - 1 \cdot \begin{vmatrix}
10 & 5\\ 
1 & 1
\end{vmatrix} + 2 \cdot \begin{vmatrix}
10 & 5\\ 
-2 & -3
\end{vmatrix} = 2 \cdot ((-2) \cdot 1 - (-3) \cdot 1) - (10 \cdot 1 - 5 \cdot 1) + 2 \cdot (10 \cdot (-3) - 5 \cdot (-2)) = 2 - 5 - 40 = -43$  

Разложение по первому столбцу:
$detA = \begin{vmatrix}
2 & -1 & 10\\ 
1 & 1 & -2\\ 
2 & 4 & 1
\end{vmatrix} = 2 \cdot \begin{vmatrix}
1 & -2\\ 
4 & 1
\end{vmatrix} - 1 \cdot \begin{vmatrix}
-1 & 10\\ 
4 & 1
\end{vmatrix} + 2 \cdot \begin{vmatrix}
-1 & 10\\ 
1 & -2
\end{vmatrix} = 2 \cdot (1 \cdot 1 - (-2) \cdot 4) - (-1 \cdot 1 - 10 \cdot 4) + 2 \cdot (-1 \cdot (-2) - 10 \cdot 1) = 18 + 41 - 16 = 43$  

$x_{1}=\frac{detA_{1}}{detA} = 86/43 = 2$  
$x_{2}=\frac{detA_{2}}{detA} = -43/43 = -1$  
$x_{3}=\frac{detA_{3}}{detA} = 43/43 = 1$

In [61]:
# проверка

In [62]:
A = Matrix([[2, -1, 5], [1, 1, -3], [2, 4, 1]])
A

Matrix([
[2, -1,  5],
[1,  1, -3],
[2,  4,  1]])

In [63]:
b = Matrix([10, -2, 1])
b

Matrix([
[10],
[-2],
[ 1]])

In [64]:
# заменяем первый столбец
A1 = A.copy()
A1.col_del(0)
A1 = A1.col_insert(0, b)
A1

Matrix([
[10, -1,  5],
[-2,  1, -3],
[ 1,  4,  1]])

In [65]:
# заменяем второй столбец
A2 = A.copy()
A2.col_del(1)
A2 = A2.col_insert(1, b)
A2

Matrix([
[2, 10,  5],
[1, -2, -3],
[2,  1,  1]])

In [66]:
# заменяем третий столбец
A3 = A.copy()
A3.col_del(2)
A3 = A3.col_insert(2, b)
A3

Matrix([
[2, -1, 10],
[1,  1, -2],
[2,  4,  1]])

In [67]:
# определитель исходной матрицы
detA = A.det()
detA

43

In [68]:
# определитель матрицы с заменой первого столбца
detA1 = A1.det()
detA1

86

In [69]:
# определитель матрицы с заменой второго столбца
detA2 = A2.det()
detA2

-43

In [70]:
# определитель матрицы с заменой третьего столбца
detA3 = A3.det()
detA3

43

In [71]:
# первое значение
x1 = detA1/detA
x1

2

In [72]:
# второе значение
x2 = detA2/detA
x2

-1

In [73]:
# третье значение
x3 = detA3/detA
x3

1

In [74]:
X = Matrix([x1, x2, x3])
X

Matrix([
[ 2],
[-1],
[ 1]])

**__2*.__ Найти $L$-матрицу $LU$-разложения для матрицы коэффициентов:  
а)$\begin{pmatrix}
1 & 2 & 4 \\ 
2 & 9 & 12 \\ 
3 & 26 & 30
\end{pmatrix}$**

Формулы нахождения элементов матриц $U$ и $L$:

$$u_{1j}=a_{1j},$$
$$l_{j1}=\frac{a_{j1}}{u_{11}}, \; u_{11}\neq0, \; j = 1,...,n.$$

Для $i = 2,...,n$:

$$u_{ij}=a_{ij}-\sum_{k=1}^{i-1}l_{ik}u_{kj},$$
$$l_{ji}=\frac{1}{u_{ii}}(a_{ji}-\sum_{k=1}^{i-1}l_{jk}u_{ki}),\; j = i,...,n.$$

In [75]:
a_11 = 1.
a_21 = 2.
a_31 = 3.
a_12 = 2.
a_22 = 9.
a_32 = 26.
a_13 = 4.
a_23 = 12.
a_33 = 30.

In [76]:
u_11 = a_11
u_11

1.0

In [77]:
u_12 = a_12
u_12

2.0

In [78]:
u_13 = a_13
u_13

4.0

In [79]:
l_11 = a_11/u_11
l_11

1.0

In [80]:
l_21 = a_21/u_11
l_21

2.0

In [81]:
l_31 = a_31/u_11
l_31

3.0

In [82]:
u_22 = a_22 - l_21 * u_12
u_22

5.0

In [83]:
l_22 = (1/u_22)*(a_22 - l_21*u_12)
l_22

1.0

In [84]:
u_23 = a_23 - l_21*u_13
u_23

4.0

In [85]:
l_32 = (1/u_22)*(a_32 - l_31*u_12)
l_32

4.0

In [86]:
u_33 = a_33 - l_31*u_13 - l_32*u_23
u_33

2.0

In [87]:
l_33 = (1/u_33)*(a_33 - l_31*u_13 - l_32*u_23)
l_33

1.0

In [88]:
L = Matrix([[l_11, 0, 0], [l_21, l_22, 0], [l_31, l_32, l_33]])
L

Matrix([
[1.0,   0,   0],
[2.0, 1.0,   0],
[3.0, 4.0, 1.0]])

In [89]:
U = Matrix([[u_11, u_12, u_13], [0, u_22, u_23], [0, 0, u_33]])
U

Matrix([
[1.0, 2.0, 4.0],
[  0, 5.0, 4.0],
[  0,   0, 2.0]])

In [90]:
L*U

Matrix([
[1.0,  2.0,  4.0],
[2.0,  9.0, 12.0],
[3.0, 26.0, 30.0]])

In [91]:
# Необходимая по условию матрица L
L

Matrix([
[1.0,   0,   0],
[2.0, 1.0,   0],
[3.0, 4.0, 1.0]])

**__2*.__ Найти $L$-матрицу $LU$-разложения для матрицы коэффициентов:  
б)$\begin{pmatrix}
1 & 1 & 2 & 4\\ 
2 & 5 & 8 & 9\\ 
3 & 18 & 29 & 18\\
4 & 22 & 53 & 33
\end{pmatrix}$**

In [92]:
a_11 = 1.
a_21 = 2.
a_31 = 3.
a_41 = 4.
a_12 = 1.
a_22 = 5.
a_32 = 18.
a_42 = 22.
a_13 = 2.
a_23 = 8.
a_33 = 29.
a_43 = 53.
a_14 = 4.
a_24 = 9.
a_34 = 18.
a_44 = 33.

In [93]:
u_11 = a_11
u_11

1.0

In [94]:
u_12 = a_12
u_12

1.0

In [95]:
u_13 = a_13
u_13

2.0

In [96]:
u_14 = a_14
u_14

4.0

In [97]:
l_11 = a_11/u_11
l_11

1.0

In [98]:
l_21 = a_21/u_11
l_21

2.0

In [99]:
l_31 = a_31/u_11
l_31

3.0

In [100]:
l_41 = a_41/u_11
l_41

4.0

In [101]:
u_22 = a_22 - l_21 * u_12
u_22

3.0

In [102]:
l_22 = (1/u_22)*(a_22 - l_21*u_12)
l_22

1.0

In [103]:
u_23 = a_23 - l_21*u_13
u_23

4.0

In [104]:
l_32 = (1/u_22)*(a_32 - l_31*u_12)
l_32

5.0

In [105]:
u_33 = a_33 - l_31*u_13 - l_32*u_23
u_33

3.0

In [106]:
l_33 = (1/u_33)*(a_33 - l_31*u_13 - l_32*u_23)
l_33

1.0

In [107]:
u_24 = a_24 - l_21*u_14
u_24

1.0

In [108]:
l_42 = (1/u_22)*(a_42 - l_41*u_12)
l_42

6.0

In [109]:
u_34 = a_34 - l_31*u_14 - l_32*u_24
u_34

1.0

In [110]:
l_43 = (1/u_33)*(a_43 - l_41*u_13 - l_42*u_23)
l_43

7.0

In [111]:
u_44 = a_44 - l_41*u_14 - l_42*u_24 - l_43*u_34
u_44

4.0

In [112]:
l_44 = (1/u_44)*(a_44 - l_41*u_14 - l_42*u_24 - l_43*u_34)
l_44

1.0

In [113]:
L = Matrix([[l_11, 0, 0, 0], [l_21, l_22, 0, 0], [l_31, l_32, l_33, 0], [l_41, l_42, l_43, l_44]])
L

Matrix([
[1.0,   0,   0,   0],
[2.0, 1.0,   0,   0],
[3.0, 5.0, 1.0,   0],
[4.0, 6.0, 7.0, 1.0]])

In [114]:
U = Matrix([[u_11, u_12, u_13, u_14], [0, u_22, u_23, u_24], [0, 0, u_33, u_34], [0, 0, 0, u_44]])
U

Matrix([
[1.0, 1.0, 2.0, 4.0],
[  0, 3.0, 4.0, 1.0],
[  0,   0, 3.0, 1.0],
[  0,   0,   0, 4.0]])

In [115]:
L*U

Matrix([
[1.0,  1.0,  2.0,  4.0],
[2.0,  5.0,  8.0,  9.0],
[3.0, 18.0, 29.0, 18.0],
[4.0, 22.0, 53.0, 33.0]])

In [116]:
# Необходимая по условию матрица L
L

Matrix([
[1.0,   0,   0,   0],
[2.0, 1.0,   0,   0],
[3.0, 5.0, 1.0,   0],
[4.0, 6.0, 7.0, 1.0]])

**__3*.__ Решить систему линейных уравнений методом $LU$-разложения $\begin{cases}
2x_{1}+x_{2}+3x_{3}=1 \\
11x_{1}+7x_{2}+5x_{3}=-6 \\
9x_{1}+8x_{2}+4x_{3}=-5
\end{cases}$**

In [117]:
# исходная матрица
A = Matrix([[2, 1, 3], [11, 7, 5], [9, 8, 4]])
A

Matrix([
[ 2, 1, 3],
[11, 7, 5],
[ 9, 8, 4]])

In [118]:
b = np.array([1, -6, -5])
b

array([ 1, -6, -5])

In [119]:
a_11 = 2.
a_21 = 11.
a_31 = 9.
a_12 = 1.
a_22 = 7.
a_32 = 8.
a_13 = 3.
a_23 = 5.
a_33 = 4.

In [120]:
u_11 = a_11
u_11

2.0

In [121]:
u_12 = a_12
u_12

1.0

In [122]:
u_13 = a_13
u_13

3.0

In [123]:
l_11 = a_11/u_11
l_11

1.0

In [124]:
l_21 = a_21/u_11
l_21

5.5

In [125]:
l_31 = a_31/u_11
l_31

4.5

In [126]:
u_22 = a_22 - l_21 * u_12
u_22

1.5

In [127]:
l_22 = (1/u_22)*(a_22 - l_21*u_12)
l_22

1.0

In [128]:
u_23 = a_23 - l_21*u_13
u_23

-11.5

In [129]:
l_32 = (1/u_22)*(a_32 - l_31*u_12)
l_32

2.333333333333333

In [130]:
u_33 = a_33 - l_31*u_13 - l_32*u_23
u_33

17.33333333333333

In [131]:
l_33 = (1/u_33)*(a_33 - l_31*u_13 - l_32*u_23)
l_33

1.0

In [132]:
L = np.array([[l_11, 0, 0], [l_21, l_22, 0], [l_31, l_32, l_33]])
L

array([[1.        , 0.        , 0.        ],
       [5.5       , 1.        , 0.        ],
       [4.5       , 2.33333333, 1.        ]])

In [133]:
U = np.array([[u_11, u_12, u_13], [0, u_22, u_23], [0, 0, u_33]])
U

array([[  2.        ,   1.        ,   3.        ],
       [  0.        ,   1.5       , -11.5       ],
       [  0.        ,   0.        ,  17.33333333]])

In [134]:
L.dot(U)

array([[ 2.,  1.,  3.],
       [11.,  7.,  5.],
       [ 9.,  8.,  4.]])

In [135]:
# решаем систему Ly = b
L

array([[1.        , 0.        , 0.        ],
       [5.5       , 1.        , 0.        ],
       [4.5       , 2.33333333, 1.        ]])

In [136]:
b

array([ 1, -6, -5])

In [137]:
# y1, y2, y3
y = np.linalg.solve(L, b)
y

array([  1.        , -11.5       ,  17.33333333])

In [138]:
# теперь решим систему Ux = y
U

array([[  2.        ,   1.        ,   3.        ],
       [  0.        ,   1.5       , -11.5       ],
       [  0.        ,   0.        ,  17.33333333]])

In [139]:
# x1, x2, x3
X = np.linalg.solve(U, y)
X

array([-1.,  0.,  1.])

In [140]:
A

Matrix([
[ 2, 1, 3],
[11, 7, 5],
[ 9, 8, 4]])

Подставим полученные значения переменных в исходную систему:  
$\begin{cases}
2\cdot(-1)+1\cdot0 + 3 \cdot1=1, \\
11\cdot(-1) + 7\cdot0 + 5\cdot1=-6, \\
9\cdot(-1)+8\cdot0+4\cdot1=5.
\end{cases}$  
Найденное решение верно.

In [141]:
# проверка
A = np.array([[2, 1, 3], [11, 7, 5], [9, 8, 4]])
A

array([[ 2,  1,  3],
       [11,  7,  5],
       [ 9,  8,  4]])

In [142]:
b = np.array([1, -6, -5])
b

array([ 1, -6, -5])

In [143]:
np.linalg.solve(A, b)

array([-1.,  0.,  1.])

**__4*.__ Решить систему линейных уравнений методом Холецкого $\begin{cases}
81x_{1}-45x_{2}+45x_{3}=531 \\
-45x_{1}+50x_{2}-15x_{3}=-460 \\
45x_{1}-15x_{2}+38x_{3}=193
\end{cases}$**

$\begin{pmatrix}
a_{11} & a_{12} & a_{13}\\ 
a_{21} & a_{22} & a_{23}\\ 
a_{31} & a_{32} & a_{33}\\ 
\end{pmatrix}
\begin{pmatrix}
x_{1}\\ 
x_{2}\\ 
x_{3}\\ 
\end{pmatrix}=
\begin{pmatrix}
b_{1}\\ 
b_{2}\\ 
b_{3}\\ 
\end{pmatrix}.$

$A = \begin{pmatrix}
81 & -45 & 45\\ 
-45 & 50 & -15\\ 
45 & -15 & 38\\ 
\end{pmatrix}$


Произведем разложение на $LL^{T}$:

$l_{11}=\sqrt{a_{11}}=\sqrt{81} = 9,$  
$l_{21}=\frac{a_{21}}{l_{11}}=\frac{-45}{9} = -5,$  
$l_{31}=\frac{a_{31}}{l_{11}}=\frac{45}{9} = 5,$  
$l_{22}=\sqrt{a_{22}-l_{21}^{2}}=\sqrt{50 - 5^{2}}=\sqrt{50 - 25} = 5,$  
$l_{32}=\frac{1}{l_{22}}\left ( a_{32}-l_{21}l_{31} \right)=\frac{1}{5}\left ( -15 - (-5)\cdot 5 \right )=\frac{-15 + 25}{5} = 10/5 = 2,$  
$l_{33}=\sqrt{a_{33}-l_{31}^{2}-l_{32}^{2}}=\sqrt{38 - 25 - 4}=3.$  

Получили матрицу:  

$L = \begin{pmatrix}
9 & 0 & 0\\ 
-5 & 5 & 0\\ 
5 & 2 & 3\\ 
\end{pmatrix}, 
\; \; 
L^{T} = \begin{pmatrix}
9 & -5 & 5\\ 
0 & 5 & 2\\ 
0 & 0 & 3\\ 
\end{pmatrix}.$

$b = \begin{pmatrix}
531\\ 
-460\\
193
\end{pmatrix}$  

Решим систему $Ly=b:$  

$\begin{cases}
9y_{1}=531, \\
-5y_{1}+5y_{2}=-460, \\
5y_{1}+2y_{2}+3y_{3}=193.
\end{cases}$  

$y_{1} = 59,$  

$y_{2}=\frac{-460 + 5\cdot59}{5}=-33,$  

$y_{3}=\frac{193 - 5 \cdot 59 + 2 \cdot 33}{3}=-12$  

Решим систему $L^{T}x=y:$

$\begin{cases}
9x_{1}-5x_{2}+5x_{3}=59, \\
5x_{2}+2x_{3}=-33, \\
3x_{3}=-12.
\end{cases}$  

$x_{3}=-4,$  

$x_{2}=\frac{-33 + 2\cdot4}{5} = -5,$  

$x_{1}=\frac{59 - 5 * 5 + 5 * 4}{9}=\frac{54}{9}=6.$  

In [144]:
# проверка

In [145]:
L = Matrix([[9, 0, 0], [-5, 5, 0], [5, 2, 3]])
L

Matrix([
[ 9, 0, 0],
[-5, 5, 0],
[ 5, 2, 3]])

In [146]:
L.T

Matrix([
[9, -5, 5],
[0,  5, 2],
[0,  0, 3]])

In [147]:
A = np.array([[81, -45, 45], [-45, 50, -15],[45, -15, 38]])
A

array([[ 81, -45,  45],
       [-45,  50, -15],
       [ 45, -15,  38]])

In [148]:
b = np.array([531, -460, 193])
b

array([ 531, -460,  193])

In [149]:
np.linalg.solve(A, b)

array([ 6., -5., -4.])